# Generated by Django 3.2.8 on 2023-01-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cements', '0002_rename_thickness_cement_bestfor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cement',
            old_name='_photo',
            new_name='cement_photo',
        ),
    ]
